# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-28 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [ ]
